Add session duration options
cshamrick/stsauth pull request #71
Opened 2023-10-02 15:48 UTC by Flurbb

2023-10-02 18:33 UTC, cshamrick requested changes

2023-10-02 18:33 UTC, cshamrick commented on README.md
Can you also update the Usage section of the readme where appropriate?

2023-10-02 19:44 UTC, phillipjf commented
This is fine with me. Just note that the upper bound on the duration is still constrained by the duration set on the role itself (or 1 hour in the case of role-chaining). See [`AssumeRole` API docs; `DurationSeconds`](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#API_AssumeRole_RequestParameters):

> The maximum session duration setting can have a value from 1 hour to 12 hours. If you specify a value higher than this setting or the administrator setting (whichever is lower), the operation fails.

> However, if you assume a role using role chaining and provide a DurationSeconds parameter value greater than one hour, the operation fails.

2023-10-02 19:45 UTC, phillipjf approved these changes

2023-10-02 19:50 UTC, cshamrick commented
> This is fine with me. Just note that the upper bound on the duration is still constrained by the duration set on the role itself (or 1 hour in the case of role-chaining). See [`AssumeRole` API docs; `DurationSeconds`](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#API_AssumeRole_RequestParameters):
> 
> > The maximum session duration setting can have a value from 1 hour to 12 hours. If you specify a value higher than this setting or the administrator setting (whichever is lower), the operation fails.
> 
> > However, if you assume a role using role chaining and provide a DurationSeconds parameter value greater than one hour, the operation fails.

@Flurbb can you test related edge-cases and make sure `stsauth` handles related errors and prints useful information back to the end-user?

2023-10-02 19:55 UTC, Flurbb commented
@cshamrick yeah can do

2023-10-02 20:55 UTC, Flurbb commented
I'm just taking out the assume role option since it's not really going to get us anything valuable

2023-10-02 23:42 UTC, phillipjf commented
> I'm just taking out the assume role option since it's not really going to get us anything valuable

It wasn't often, but I had a few use cases that I leveraged this functionality for managing assume-role permissions.

2023-10-03 01:28 UTC, Flurbb commented
> > I'm just taking out the assume role option since it's not really going to get us anything valuable
> 
> It wasn't often, but I had a few use cases that I leveraged this functionality for managing assume-role permissions.

Oh I'm not taking out the assume role functionality, I'm taking out the option I added to change the duration of assume-role sessions to be something different than 1 hour. There's no functionality regression

2023-10-03 14:37 UTC, cshamrick approved these changes

2023-10-03 16:57 UTC, merged

2023-10-03 17:47 UTC, cshamrick commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/cshamrick/stsauth/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: